/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('@iconify/vue')['Icon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VLayout: typeof import('./core/components/layouts/VLayout.vue')['default']
    VLayoutBlank: typeof import('./core/components/layouts/VLayoutBlank.vue')['default']
    VLayoutDefault: typeof import('./core/components/layouts/VLayoutDefault.vue')['default']
  }
}
